# Generated by Django 4.2.9 on 2024-02-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_url", models.CharField(default="", max_length=300)),
                ("output_filename", models.CharField(default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
