# Generated by Django 4.2.9 on 2024-02-03 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transcript", old_name="input_url", new_name="input_data",
        ),
    ]
