# Generated by Django 4.2.9 on 2024-02-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_input_url_transcript_input_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcript",
            name="input_file",
            field=models.FileField(default="models.py", upload_to=""),
        ),
    ]
